#When opening pgadmin in localhost:8080 enter the following to connect to the database:
# Add server:
# Name: Docker localhost
# Conection:
# Host name/address: pgdatabase
# Username: root
# Password: root

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER="root"
      - POSTGRES_PASSWORD="root"
      - POSTGRES_DB="ny_taxi"
    volumes:
      #hostpath:containerpath:mode . RW = Read Write
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"